name: Builds

on:
  push:
    branches: [ master ]

jobs:
  Linux_Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          cache: 'pip'
  
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build with PyInstaller
        run: python build.py
        
      - uses: actions/upload-artifact@v3
        with:
          name: Linux Build
          path: dist/

  Windows_Build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.5'
          cache: 'pip'
  
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Build with PyInstaller
        run: python build.py
        
      - uses: actions/upload-artifact@v3
        with:
          name: Windows Build
          path: dist/